# spring configuration
spring:
  # dbconfig
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/lims
    driver-class-name: com.mysql.cj.jdbc.Driver

  # jpa config
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQLDialect"
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# enable graceful shutdown
server:
  shutdown: graceful

# actuator shutdown
management:
  endpoint:
    shutdown:
      enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"